# Generated by Django 2.1.2 on 2018-11-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Restaurant'),
        ),
    ]
