# Generated by Django 2.1.2 on 2018-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181130_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrecord',
            name='until',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
