pdf: project-requirements-and-specification.pdf
project-requirements-and-specification.pdf: Project-Requirements-and-Specification.md
	pandoc \
		-F pandoc-latex-color \
		Project-Requirements-and-Specification.md \
		-o project-requirements-and-specification.pdf
clean:
	rm -f project-requirements-and-specification.pdf
