coverage:
  status:
    project:
      default: off
      frontend:
        flags: frontend
      backend:
        flags: backend

  flags:
    backend:
      paths:
        - backend/
    frontend:
      paths:
        - frontend/
