pdf: design-and-planning.pdf
design-and-planning.pdf: Design-and-Planning.md
	pandoc \
		-F pandoc-latex-color \
		Design-and-Planning.md \
		-o design-and-planning.pdf
clean:
	rm -f design-and-planning.pdf
